interface IFooter {
    title:string,
    id: number,
}
export const footerData:IFooter [] = [
    {
        title:"footer.aboutUs_title",
        id:1,
    },
    {
        title:"footer.news_services_title",
        id:2,
    },
    {
        title:"footer.help_title",
        id:3,
    },
    {
        title:"footer.employers_title",
        id:4,
    },
    {
        title:"footer.post_a_job_title",
        id:5,
    },
    {
        title:"footer.resumeSection_title",
        id:6,
    },
    {
        title:"footer.applicants_title",
        id:7,
    },
    {
        title:"footer.addResume_title",
        id:8,
    },
    {
        title:"footer.section_of_vacancies_title",
        id:9,
    },
    {
        title:"footer.companies_title",
        id:10,
    },
    
    {
        title:"compas",
        id:13
    }
]